#!/bin/bash
gr ${1} &
if ! [ -f ~/.Gwords/dict/${1}.html ]; then

    if ! [ -d ~/.Gwords/dict ]; then
        mkdir -p ~/.Gwords/dict
    fi

    cd ~/.Gwords/dict
    curl -s -o "${1}.html" http://www.iciba.com/${1}
fi

html=`cat ~/.Gwords/dict/${1}.html | tr [:space:] ' '`
c=`echo $html | 
    sed 's/.*article\ info\-base/</' | 
    sed -e 's/_trackEvent.*/>/g' | 
    sed -e 's/<span>[^<.英美]*nbsp;\/<\/span>//g' | 
    sed -e 's/<span>IELTS<\/span>//g' | 
    sed -e 's/<span/\\\n</g'`
cn=`echo $c | sed -e 's/<[^<]*>//g'`
if [[ `echo -e $cn | wc -l` -lt 20 ]]; then
    echo -e $cn
fi

s="<'"`echo $html | sed -e 's/.*双语例句\ start//' | sed -e 's/双语例句\ end.*//'`">"
sn=`echo $s | 
    sed -e 's/p-order/>\\\n</g' | 
    sed -e 's/<[^<]*>//g' | 
    sed -e 's/^.*收起\ *\\\n/\\\n/' | 
    sed -e 's/来自[A-Za-z .]*//g' | 
    sed -e 's/查看更多//g' | 
    sed -e 's/《[^0-9]*》//g'`
if [[ `echo -e $sn | wc -l` -lt 20 ]]; then
    echo -e "$sn"
fi

if [[ `echo -e $cn | wc -l` -gt 30 ]]; then
    rm ~/.Gwords/dict/${1}.html
fi

if [[ `echo -e $sn | wc -l` -gt 50 ]]; then
    rm ~/.Gwords/dict/${1}.html
fi
