#!/bin/bash
if [[ `uname` == 'Darwin' || `uname` == 'darwin' ]]; then
  exit 0
fi

function download_pic () {
  if ! [ -d ~/.Gwords/img ]; then
      mkdir -p ~/.Gwords/img
  fi
  if ! [ -f ~/.Gwords/img/${1}.jpg ]; then
    youdao_img_html=`curl -s "http://image.youdao.com/search?q=${1}" |
        grep "img border" |
        grep "jpg" |
        head -1`
    cd ~/.Gwords/img
    b=${youdao_img_html#*src=\"}
    c=${b%%\"*}
    curl -s -o "${1}.jpg" ${c}
  fi
}

if ! [ ${1} ]; then
  rand=`head -200 /dev/urandom | cksum | cut -f1 -d" "`
  sn=$(( rand % GWORDS_COUNT / 2 ))
  #sn=$(( rand % GAOBIN_WORD_COUNT / 2 ))
  ind=$(( sn * 2 + 1))
  en=`sed -n $(( ind + 0 )),1p ~/.Gwords/list.txt | tr [:space:] ' '`
  en=${en%%\ *}
  zh=`sed -n $(( ind + 1 )),1p ~/.Gwords/list.txt | tr [:space:] ' '`
  download_pic $en $en
  notify-send -t 7 -i "${HOME}/.Gwords/img/${en}.jpg" "$en" "$zh"
  gr $en & >/dev/null
else
  download_pic "${1}"
  notify-send -t 7 -i "${HOME}/.Gwords/img/${1}.jpg" "${1}" "`gd ${1} | sed -n '2,10p' | grep -v ^$ | head -7`"
fi



